const fs=require("fs");const {Document,Packer,Paragraph,TextRun,HeadingLevel,AlignmentType,LevelFormat}=require("docx");
const F="Arial";
const P=(parts,o={})=>new Paragraph({children:(Array.isArray(parts)?parts:[parts]).map(p=>typeof p==="string"?new TextRun({text:p,font:F,size:22}):new TextRun(Object.assign({font:F,size:22},p))),spacing:{after:140,line:300},numbering:o.num?{reference:o.num,level:0}:undefined});
const H=(t)=>new Paragraph({children:[new TextRun({text:t,bold:true,font:F,size:30,color:"B10202"})],spacing:{before:300,after:120}});
const H2=(t)=>new Paragraph({children:[new TextRun({text:t,bold:true,font:F,size:24})],spacing:{before:200,after:80}});
const QA=(q,a)=>[P([{text:"Q: "+q,bold:true}]),P("A: "+a)];
const c=[];
c.push(new Paragraph({children:[new TextRun({text:"Symposium Presenter Notes",bold:true,font:F,size:36})],alignment:AlignmentType.CENTER}));
c.push(new Paragraph({children:[new TextRun({text:"Decentralized, Browser-Based Docker IDEs for C++ and x86-64 Assembly Education",font:F,size:22})],alignment:AlignmentType.CENTER,spacing:{after:300}}));

c.push(H("How to use this sheet"));
c.push(P("Most visitors give you 30 seconds before deciding whether to stay. Open with the one-sentence version, then the 90-second version, then walk the poster only if they are still with you. Point at the poster as you go: hook strip, then left column, middle, right, bottom. Every number you say is printed somewhere on the poster, so you never have to remember one under pressure."));

c.push(H("The one-sentence version (for anyone)"));
c.push(P([{text:"“I built a way for every student in two UNLV programming courses to get the exact same working setup with one download, and then I tested whether it really works on the kinds of laptops students actually own.”",italic:true}]));

c.push(H("The 90-second version"));
c.push(P("1. The problem. Every semester, hundreds of students in UNLV’s introductory C++ and assembly courses lose their first week to installing software instead of learning. Students with the newest Macs sometimes cannot run the course’s tools at all. This is not just UNLV; other universities measured 75 to 100 minutes of class time per semester lost to installs."));
c.push(P("2. What I built. I packaged each course’s exact tools plus a code editor into a container, which is a sealed, pre-configured copy of the tools that runs inside any laptop. The student installs one free program, runs one command, and opens a browser tab. Nothing runs on a server, no account is needed, and nothing is recorded."));
c.push(P("3. The research question. It worked on my laptop. The fellowship asked: does it work on the laptops students actually own, what does it cost them, and where does it break?"));
c.push(P("4. How I tested it. I could not borrow every kind of laptop, so I rented them: a Windows 11 machine, an Intel Linux machine, and an ARM Linux machine from the cloud for under ten dollars total, plus my own base-model M1 MacBook. I ran one unchanged script on each that did a student’s first day: download, open the editor, write and run programs, try the debugger, build four real CS 218 assignments, then delete the container and check that the student’s files survive."));
c.push(P("5. What I found. All four machines ran every assignment correctly. The editor opens in half a second on Intel chips and about five seconds on Apple Silicon. The download is 552 megabytes instead of the 19 gigabyte virtual machine the course uses today. The one limit is the debugger: it works on Intel machines and goes silent on Apple Silicon and other ARM chips, because those chips run the Intel-style software through a translator that does not support debugging. The student handout tells Mac owners exactly what to do."));
c.push(P("6. Why it matters. Week one goes to learning. The department has no servers to maintain. And the trade-off (keep the real instruction set the course teaches, lose the debugger on ARM) is now measured instead of guessed. Next is a classroom study."));

c.push(H("Walking the poster, section by section"));
c.push(H2("The hook (pink strip)")); c.push(P("Read the bold sentence out loud. Then: “The question I asked is the last sentence: can the whole course environment be one download that works the same on every laptop, and how would we know?”"));
c.push(H2("Three terms (right side of the strip)")); c.push(P("If someone looks lost, point here. Container = sealed copy of the tools. Translation = how a Mac chip runs Intel software, correct but slower. Debugger = a tool that pauses a program so you can look inside."));
c.push(H2("Introduction and background (left column)")); c.push(P("“Universities have tried four things.” Walk the numbered list: shared servers you log in to (UNLV did this for twenty years; they are gone now), a virtual machine per course (UNLV does this today; it is 19 GB and barely works on new Macs), cloud editors like Harvard’s CS50 (needs internet and an account), and monitored platforms like CodeDive in South Korea (records every keystroke pause). “Mine is a fifth option: the container runs on the student’s own laptop.”"));
c.push(H2("Problem and research focus (left column, bottom)")); c.push(P("Three questions: does it behave identically everywhere, what does it cost, and where does it break. Say: “I deliberately did not ask how students feel about it yet; that needs a classroom study, which is the next step.”"));
c.push(H2("Methodology (middle column)")); c.push(P("Point at the black command box: “This is the entire setup for a student.” Point at Figure 1: “Everything inside the red box is the container; the student’s files live outside it in a normal folder, so deleting the container never loses work.” Then the four machine cards and the five-step script. Emphasize: same script, unchanged, on all four; it writes every number to a file; nothing on the poster was typed by hand."));
c.push(H2("Results (right column)")); c.push(P("Three big numbers first: 4 of 4, 0.5 seconds, 552 MB. Then the table: two green “works” and two red “silent” in the debugger row is the whole story. Then the bar chart: Intel machines are the two short bars. Then “the one limit, in plain words.”"));
c.push(H2("Concluding discussion (bottom)")); c.push(P("Four cards: students, the department, other researchers, and what comes next. If time is short, read only the first sentence of each."));

c.push(H("Numbers to have in your head (all printed on the poster)"));
c.push(P("4 of 4 machines passed all four assignments.  ·  Editor ready: 0.5 s Linux Intel, 0.6 s Windows, 4.8 s M1 Mac, 6.7 s Linux ARM.  ·  Download: 552 MB, versus a 19 GB course VM.  ·  Memory while idle: about 55 MiB on Intel, about 260 MiB under translation.  ·  Heaviest assignment builds in under a second on Intel, under four seconds under translation (about ten times slower).  ·  Cloud rental: under $10 total.  ·  Prior work: 75–100 minutes per semester lost to installs [6]."));

c.push(H("Questions you are likely to get, with short answers"));
[
["What is Docker? What is a container?","Docker is a free program that runs containers. A container is a sealed, pre-configured copy of a set of tools, so every student gets exactly the versions the instructor chose. It is lighter than a virtual machine because it shares the laptop’s own operating system core instead of carrying a whole second computer."],
["How is this different from the virtual machine the course already uses?","A virtual machine is a copy of an entire computer: 19 GB, minutes to boot, and it reserves a chunk of memory whether you use it or not. The container is 552 MB, opens in seconds, and uses about 55 MB of memory when idle. And it is the identical file on Windows, Mac, and Linux."],
["Why not just use the cloud, like Harvard does?","Harvard’s approach works very well, but it needs an internet connection, a GitHub account, and a company willing to host it, and Harvard reports students finishing the course still unsure how to set up their own computer. My design puts the same container on the student’s laptop instead: it works offline, nothing leaves the machine, and the student owns the environment."],
["Why does the debugger break on Macs?","The assembly course teaches the Intel-style x86-64 instruction set, so the container is built for Intel chips on purpose. Apple Silicon runs it through a translator. The translator runs programs correctly but does not support the debugger’s way of pausing and inspecting a program, so the debugger appears to run and writes nothing useful. That happens with both translators I tested, so it is a limit of translation, not a bug in my container."],
["Isn’t that a big problem for Mac users?","It is a real limit and I say so on the poster and in the handout. Everything except the debugger works on a Mac, and only some assignments need the debugger; for those, the handout tells students to use a lab machine or any Intel computer. The next step is a hybrid container that translates only the student’s program, which could bring the debugger back."],
["Did students actually use it?","The C++ container has been used by one three-student high-school class; no metrics or surveys were collected, so I report it only as a first deployment. The measurements on this poster are machine measurements. The classroom study with IRB approval is the next stage."],
["Why did you rent computers instead of asking students?","Because I wanted a clean, blank machine of each kind so that the only thing that differed was the computer itself, and so that anyone can repeat the experiment for a few dollars. Student laptops have years of other software on them, which would confuse the results."],
["How much did it cost?","Under ten dollars for all the cloud machines, and the MacBook was mine. Students pay nothing and need no account."],
["What about privacy and AI?","Nothing is recorded or sent anywhere; the container has no telemetry. Every AI feature in the editor is switched off, so AI use is governed by the course policy, not by the tool. That is a deliberate contrast with monitored platforms like CodeDive."],
["What did you personally do?","I built both containers and the student handouts, published them, wrote the measurement script, chose and verified the four assignments, set up and ran every cloud machine by hand, diagnosed the failures, read and summarized the nine papers, and wrote the report and this poster. My mentor, Dr. Andro-Vasko, provided the course requirements and guidance on which claims the evidence supports."],
["What was the hardest part?","Getting the ARM Linux machine to run at all. The translator that ships with Ubuntu crashed while translating the editor itself. I reproduced it, captured the diagnostics, and found that Docker’s own translator works. That is now one line in the handout."],
["What would you do differently?","Test on a physical Intel Mac and a Windows-on-ARM laptop; neither could be rented from any cloud. Both are stated as expectations, not results."],
].forEach(([q,a])=>c.push(...QA(q,a)));

c.push(H("If you blank"));
c.push(P("Say: “Let me show you the one number that matters.” Point at the debugger row of the table: two work, two are silent. Then: “Everything else passed everywhere. That row is the trade-off I measured.” That sentence is the whole project."));

const doc=new Document({sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1440,bottom:1440,left:1440,right:1440}}},children:c}]});
Packer.toBuffer(doc).then(b=>{fs.writeFileSync("notes.docx",b);console.log("wrote notes.docx")});
